require_relative "./martial_arts/version"
require_relative "./martial_arts/cli"
require_relative "./martial_arts/styles"
require_relative "./martial_arts/countries"
require_relative "./martial_arts/fighting_focus"
